# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init
          command: terraform init -backend-config="backend.tf" -backend-config="access_key=$aws_access_key" -backend-config="secret_key=$aws_secret_key"
      - run:
          name: terraform apply
          command: terraform apply -auto-approve -var "availability_zone=$availability_zone" -var "aws_access_key=$aws_access_key" -var "aws_region=$aws_region" -var "aws_secret_key=$aws_secret_key" -var "mgmt_ip_allowed=$mgmt_ip_allowed"
